name: hmgs_arena
description: Oyunlastirilmis HMGS sinav hazirlik uygulamasi
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  google_mobile_ads: ^6.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/question_manifest.json
    - assets/questions_seed.json
    - assets/hmgs_arena_icon.svg
    - assets/zeus_hmgs.svg
